name: Build and deploy
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node 12
        uses: actions/setup-node@v1.4.2
      
      - name: Install Node.js Dependencies
        run: npm install
      
      - run: npm run build
