name: Build and deploy
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node 12
        uses: actions/setup-node@v1.4.2
      
      - name: Cache node modules
        uses: actions/cache@v2.0.0
        with:
          path: ./node_modules
          key: ${{ runner.os }}-gatsby-website-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install Node.js Dependencies
        run: npm install
      
      - run: npm test
      
      - run: npm run build
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
     
      - name: Save public folder
        uses: actions/upload-artifact@v2
        with:
          path: public
          name: public

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
     
      - name: Download public folder
        uses: actions/download-artifact@v2
        with:
          name: public
          path: files-to-deploy
     
      - name: Upload files to S3
        run: aws s3 sync ./files-to-deploy s3://rafaels.dev --acl public-read --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1T9PRMLBJNKWL --paths "/index.html"
          aws cloudfront create-invalidation --distribution-id E2RLV0KRUYXD3U --paths "/index.html"
          aws cloudfront create-invalidation --distribution-id EWKMHRFAABPOH --paths "/index.html"