name: Build and deploy
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node 12
        uses: actions/setup-node@v1.4.2
      
      - name: Cache node modules
        uses: actions/cache@v2.0.0
        with:
          path: ./node_modules
          key: ${{ runner.os }}-gatsby-website-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install Node.js Dependencies
        run: npm install
      
      - run: npm run build
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
     
      - name: Upload files to S3
        run: aws s3 sync ./public s3://rafaels.dev --acl public-read --delete
